import type { TrackMember } from "../TrackDefinition";

export const editedTrack = {
  label: "New Track",
  description: "A hand-authored Neon Swarm track.",
  durationSeconds: 26,
  startingGun: "pulsePistol",
  startingGunLevel: 1,
  viewport: {
    orientation: "portrait",
    aspectWidth: 9,
    aspectHeight: 16,
    logicalWidth: 450,
    logicalHeight: 800,
  },
  environment: {
    floorColor: "deepBlue",
    crackColor: "cyan",
    airColor: "violet",
    horizonColor: "pink",
    pulseRate: 1.35,
    crackDensity: 14,
    airStreakCount: 11,
  },
  definition: {
    layout: `
..... | .....
..... | .....
..... | ..P..
..... | .....
..... | .....
..... | .....
..... | .....
..... | ..P..
..... | .....
..... | .....
..... | .....
..... | ..P..
..... | .....
..... | .....
..P.. | .....
..... | ..E..
..... | .....
..... | .....
..P.. | .....
..... | .....
..... | .....
..... | .....
..... | .....
..... | .....
..G.. | .....
`,
    legend: {
      ".": { id: "empty" },
      "P": { id: "enemy.basic" },
      "E": { id: "pickup.weapon.gun.splitterRifle" },
      "G": { id: "player.start" },
    },
    balance: {
      enemyHp: 1,
      enemySpeed: 1,
    },
  },
} satisfies TrackMember;
