import type { TrackDefinition } from "../TrackDefinition";

export const firstTrack = {
  layout: `
..... | .....
..... | ..E..
..... | .....
..E.. | .....
..... | .....
.E.E. | ..E..
..... | .....
..E.. | .E.E.
..... | .....
..... | .....
.EEE. | .....
..... | .....
..E.. | .EEE.
..... | .....
..... | .....
.EE.. | ..EE.
..... | .....
..E.. | .E.E.
..... | .....
..2.. | .....
.EEE. | .....
..... | ..E..
..... | .....
..E.. | .....
..P.. | ..P..
`,

  legend: {
    ".": { id: "empty" },
    "P": { id: "player.start" },
    "E": { id: "enemy.basic" },
    "2": { id: "pickup.unitMultiplier.2x", speed: 0.8 },
  },

  balance: {
    enemyHp: 1,
    enemySpeed: 1,
  },
} satisfies TrackDefinition;
