import type { TrackMember } from "../TrackDefinition";

export const generatedTrack: TrackMember = {
  label: "First Glow",
  description: "A short teaching run with a weapon in reach, one lane at a time, then a calm two-lane finish.",
  durationSeconds: 28,
  startingGun: "pulsePistol",
  startingGunLevel: 1,
  environment: {
    sceneId: "neonHall",
  },
  definition: {
    layout: `
..... | .....
..E.. | .....
..... | .....
..... | ..E..
..... | .....
..2.. | .....
..... | .....
..E.. | .....
..... | ..E..
..... | .....
..S.. | .....
..... | .....
.E... | .....
..... | ...E.
..... | .....
..a.. | .....
..... | .....
..E.. | ..E..
..... | .....
.E... | ...E.
..... | .....
..G.. | .....
..... | .....
..E.. | .....
..... | ..E..
..... | .....
..G.. | .....
..M.. | .....
`,
    legend: {
      ".": { id: "empty" },
      "M": { id: "player.start" },
      "E": { id: "enemy.basic" },
      "G": { id: "pickup.weapon.gun.pulsePistol", speed: 1.15 },
      "S": { id: "pickup.weapon.shield.lightGuard", speed: 0.92 },
      "a": { id: "pickup.weapon.sword.arcBlade", speed: 0.95 },
      "2": { id: "pickup.unitMultiplier.2x", speed: 0.9 },
    },
    balance: {
      enemyHp: 1,
      enemySpeed: 0.92,
    },
  },
} satisfies TrackMember;
