import type { TrackMember } from "../TrackDefinition";

export const generatedTrack: TrackMember = {
  label: "Level 1: First Glow",
  description: "A gentle onboarding run: early tension, a quick power-up beat, then easy escalating waves for a first-time player.",
  durationSeconds: 25,
  startingGun: "pulsePistol",
  startingGunLevel: 1,
  environment: {
    sceneId: "neonHall",
  },
  definition: {
    layout: `
..... | .....
..E.. | .....
..... | ..E..
.E... | .....
..... | .....
..G.. | .....
..... | ..2..
..... | .....
..E.. | ..E..
..... | .....
.S... | .....
..... | .....
.E.E. | .....
..... | ..E..
..a.. | .....
..... | .....
.E.E. | ..E..
..... | .....
..E.. | .E.E.
..... | .....
.E... | ..E..
..... | .....
..... | ...E.
..G.. | .....
..P.. | .....
`,
    legend: {
      ".": { id: "empty" },
      "P": { id: "player.start" },
      "E": { id: "enemy.basic" },
      "G": { id: "pickup.weapon.gun.pulsePistol", speed: 1 },
      "S": { id: "pickup.weapon.shield.lightGuard", speed: 1 },
      "a": { id: "pickup.weapon.sword.arcBlade", speed: 1 },
      "2": { id: "pickup.unitMultiplier.2x", speed: 1 },
    },
    balance: {
      enemyHp: 1.0,
      enemySpeed: 1,
    },
  },
} satisfies TrackMember;
