import type { TrackMember } from "../TrackDefinition";

export const generatedTrack: TrackMember = {
  label: "Level 4: Violet Surge",
  description: "The fourth run doubles the endurance test again, adding denser waves, bigger pickup timing decisions, and higher-tier tools while staying readable and fair.",
  durationSeconds: 120,
  startingGun: "pulsePistol",
  startingGunLevel: 1,
  environment: {
    sceneId: "neonHall",
  },
  definition: {
    layout: `
..... | .....
..E.. | .....
..... | ..E..
.E... | .....
..... | .E...
..G.. | .....
..... | ..2..
..... | .....
..E.. | ..E..
..... | .....
S.... | .....
..... | .....
.E.E. | .....
..... | ..E..
W.a.. | ....W
..... | .....
.E.E. | ..E..
..... | .....
..E.. | .E.E.
..... | .....
..I.. | ..T..
..... | .....
.E.E. | ..E..
..... | .....
..E.. | .E.E.
..... | .....
.E.E. | .E.E.
..... | .....
..2.. | .....
W.... | ....W
..E.. | ..E..
.E.E. | .....
..... | .E.E.
..E.. | ..E..
..... | .....
....b | .....
..T.. | .....
WE.E. | ..E.W
..E.. | .....
..... | .E.E.
.E.E. | ..E..
..... | .....
..J.. | .....
..... | .....
.E.E. | .E.E.
..E.. | ...P.
..... | ..EP.
.E.E. | ..EP.
..... | ...P.
..S.. | ...P.
..... | ...P.
.E.E. | .E.E.
..E.. | ..E..
..... | .....
.E.E. | ..E..
.P... | .E.E.
.PE.. | .....
.P... | .....
.PE.. | .E.E.
.P... | .....
.P... | ..K..
..... | .....
.E.E. | .E.E.
..E.. | ..E..
..... | .....
..2.. | .....
..... | .....
EEE.. | .....
..... | ..EEE
.E.E. | .E.E.
..... | .....
..X.. | .....
..... | .....
..E.. | ..E..
.E.E. | .....
..... | .E.E.
..E.. | ..E..
..... | .....
....c | .....
..... | .....
.E.E. | .E.E.
..E.. | ..E..
..... | .....
EEE.. | ..E..
..... | ..EEE
.E.E. | .....
..... | .E.E.
..E.. | ..E..
..... | .....
..2.. | .....
..... | .....
.E.E. | .E.E.
..E.. | .....
..... | ..E..
..E.. | .E.E.
..... | .....
..J.. | .....
..... | .....
.E.E. | .E.E.
..E.. | ..E..
..... | .....
.E.E. | ..EEE
..... | .....
..X.. | .....
..... | .....
.EE.. | ..E..
..... | .E.E.
.E... | .E...
..... | .....
..E.. | ..E..
...E. | .....
..H.. | ...E.
..E.. | ..E..
..... | .....
.E... | ...E.
..E.. | ..E..
..E.. | ..L..
..S.. | ..K..
..b.. | .....
..M.. | .....
`,
    legend: {
      ".": { id: "empty" },
      "E": { id: "enemy.basic" },
      "G": { id: "pickup.weapon.gun.pulsePistol", speed: 1.2 },
      "2": { id: "pickup.unitMultiplier.2x", speed: 0.8 },
      "S": { id: "pickup.weapon.shield.lightGuard", speed: 0.8 },
      "W": { id: "enemy.winger" },
      "a": { id: "pickup.weapon.sword.arcBlade", speed: 0.85 },
      "I": { id: "pickup.weapon.gun.burstCarbine", speed: 0.85 },
      "T": { id: "enemy.tank" },
      "b": { id: "pickup.weapon.sword.cleaver", speed: 0.9 },
      "J": { id: "pickup.weapon.gun.heavyCannon", speed: 0.9 },
      "P": { id: "enemy.glassShield" },
      "K": { id: "pickup.weapon.gun.splitterRifle", speed: 0.95 },
      "X": { id: "pickup.weapon.shield.hexGuard", speed: 0.95 },
      "c": { id: "pickup.weapon.sword.needleRapier", speed: 0.95 },
      "H": { id: "pickup.weapon.gun.needlerSmg" },
      "L": { id: "pickup.weapon.sword.cleaver" },
      "M": { id: "player.start" },
    },
    balance: {
      enemyHp: 1.0,
      enemySpeed: 1,
    },
  },
} satisfies TrackMember;
